[project]
name = "leet"
version = "0.1.0"
description = "Practicing stuff"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipython>=8.18.1",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "ty>=0.0.1a24",
]
